"""Task metadata and fixture data for bug_triage_medium."""

from __future__ import annotations

TASK_ID = "bug_triage_medium"
DIFFICULTY = "medium"
DESCRIPTION = "15 mixed-quality tickets, several duplicates"
TASK_DATA = {'task_id': 'bug_triage_medium',
 'step_budget': 80,
 'available_teams': ['backend-api',
                     'frontend-web',
                     'mobile-ios',
                     'mobile-android',
                     'infrastructure',
                     'data-platform'],
 'available_components': ['api-gateway',
                          'auth-service',
                          'user-service',
                          'payment-service',
                          'web-app',
                          'ios-app',
                          'android-app',
                          'database',
                          'cache',
                          'cdn'],
 'tickets': [{'ticket_id': 'BUG-2001',
              'title': 'api-gateway incident pattern 1',
              'description': 'Observed issue in api affecting user workflows. Signal quality is '
                             'high and triage is required.',
              'reporter_type': 'user',
              'service': 'api',
              'component_candidates': ['api-gateway', 'auth-service', 'payment-service'],
              'created_at': '2024-02-01T09:00:00',
              'customer_tier': 'enterprise',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 1,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2002',
              'title': 'auth-service incident pattern 2',
              'description': 'Observed issue in auth affecting user workflows. Signal quality is '
                             'low and triage is required.',
              'reporter_type': 'qa',
              'service': 'auth',
              'component_candidates': ['auth-service', 'user-service', 'web-app'],
              'created_at': '2024-02-01T09:13:00',
              'customer_tier': 'pro',
              'repro_steps_present': False,
              'logs_present': False,
              'attachments_count': 2,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2003',
              'title': 'user-service incident pattern 3',
              'description': 'Observed issue in identity affecting user workflows. Signal quality '
                             'is low and triage is required.',
              'reporter_type': 'monitoring',
              'service': 'identity',
              'component_candidates': ['user-service', 'payment-service', 'ios-app'],
              'created_at': '2024-02-01T09:26:00',
              'customer_tier': 'free',
              'repro_steps_present': False,
              'logs_present': True,
              'attachments_count': 3,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2004',
              'title': 'payment-service incident pattern 4',
              'description': 'Observed issue in payments affecting user workflows. Signal quality '
                             'is high and triage is required.',
              'reporter_type': 'user',
              'service': 'payments',
              'component_candidates': ['payment-service', 'web-app', 'android-app'],
              'created_at': '2024-02-01T09:39:00',
              'customer_tier': 'enterprise',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 4,
              'suspected_duplicate_ids': ['BUG-2002']},
             {'ticket_id': 'BUG-2005',
              'title': 'web-app incident pattern 5',
              'description': 'Observed issue in web-app affecting user workflows. Signal quality '
                             'is high and triage is required.',
              'reporter_type': 'qa',
              'service': 'web-app',
              'component_candidates': ['web-app', 'ios-app', 'database'],
              'created_at': '2024-02-01T09:52:00',
              'customer_tier': 'pro',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 1,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2006',
              'title': 'ios-app incident pattern 6',
              'description': 'Observed issue in mobile-app affecting user workflows. Signal '
                             'quality is low and triage is required.',
              'reporter_type': 'monitoring',
              'service': 'mobile-app',
              'component_candidates': ['ios-app', 'android-app', 'cache'],
              'created_at': '2024-02-01T10:05:00',
              'customer_tier': 'enterprise',
              'repro_steps_present': False,
              'logs_present': False,
              'attachments_count': 2,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2007',
              'title': 'android-app incident pattern 7',
              'description': 'Observed issue in mobile-app affecting user workflows. Signal '
                             'quality is high and triage is required.',
              'reporter_type': 'user',
              'service': 'mobile-app',
              'component_candidates': ['android-app', 'database', 'cdn'],
              'created_at': '2024-02-01T10:18:00',
              'customer_tier': 'pro',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 3,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2008',
              'title': 'database incident pattern 8',
              'description': 'Observed issue in analytics affecting user workflows. Signal quality '
                             'is low and triage is required.',
              'reporter_type': 'qa',
              'service': 'analytics',
              'component_candidates': ['database', 'cache', 'api-gateway'],
              'created_at': '2024-02-01T10:31:00',
              'customer_tier': 'free',
              'repro_steps_present': False,
              'logs_present': True,
              'attachments_count': 4,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2009',
              'title': 'cache incident pattern 9',
              'description': 'Observed issue in infra affecting user workflows. Signal quality is '
                             'high and triage is required.',
              'reporter_type': 'monitoring',
              'service': 'infra',
              'component_candidates': ['cache', 'cdn', 'auth-service'],
              'created_at': '2024-02-01T10:44:00',
              'customer_tier': 'enterprise',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 1,
              'suspected_duplicate_ids': ['BUG-2005']},
             {'ticket_id': 'BUG-2010',
              'title': 'cdn incident pattern 10',
              'description': 'Observed issue in media affecting user workflows. Signal quality is '
                             'high and triage is required.',
              'reporter_type': 'user',
              'service': 'media',
              'component_candidates': ['cdn', 'api-gateway', 'user-service'],
              'created_at': '2024-02-01T10:57:00',
              'customer_tier': 'pro',
              'repro_steps_present': True,
              'logs_present': False,
              'attachments_count': 2,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2011',
              'title': 'api-gateway incident pattern 11',
              'description': 'Observed issue in api affecting user workflows. Signal quality is '
                             'high and triage is required.',
              'reporter_type': 'qa',
              'service': 'api',
              'component_candidates': ['api-gateway', 'auth-service', 'payment-service'],
              'created_at': '2024-02-01T11:10:00',
              'customer_tier': 'enterprise',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 3,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2012',
              'title': 'auth-service incident pattern 12',
              'description': 'Observed issue in auth affecting user workflows. Signal quality is '
                             'low and triage is required.',
              'reporter_type': 'monitoring',
              'service': 'auth',
              'component_candidates': ['auth-service', 'user-service', 'web-app'],
              'created_at': '2024-02-01T11:23:00',
              'customer_tier': 'pro',
              'repro_steps_present': False,
              'logs_present': True,
              'attachments_count': 4,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2013',
              'title': 'user-service incident pattern 13',
              'description': 'Observed issue in identity affecting user workflows. Signal quality '
                             'is high and triage is required.',
              'reporter_type': 'user',
              'service': 'identity',
              'component_candidates': ['user-service', 'payment-service', 'ios-app'],
              'created_at': '2024-02-01T11:36:00',
              'customer_tier': 'free',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 1,
              'suspected_duplicate_ids': []},
             {'ticket_id': 'BUG-2014',
              'title': 'payment-service incident pattern 14',
              'description': 'Observed issue in payments affecting user workflows. Signal quality '
                             'is high and triage is required.',
              'reporter_type': 'qa',
              'service': 'payments',
              'component_candidates': ['payment-service', 'web-app', 'android-app'],
              'created_at': '2024-02-01T11:49:00',
              'customer_tier': 'enterprise',
              'repro_steps_present': True,
              'logs_present': False,
              'attachments_count': 2,
              'suspected_duplicate_ids': ['BUG-2001']},
             {'ticket_id': 'BUG-2015',
              'title': 'web-app incident pattern 15',
              'description': 'Observed issue in web-app affecting user workflows. Signal quality '
                             'is high and triage is required.',
              'reporter_type': 'monitoring',
              'service': 'web-app',
              'component_candidates': ['web-app', 'ios-app', 'database'],
              'created_at': '2024-02-01T12:02:00',
              'customer_tier': 'pro',
              'repro_steps_present': True,
              'logs_present': True,
              'attachments_count': 3,
              'suspected_duplicate_ids': []}],
 'ground_truths': [{'ticket_id': 'BUG-2001',
                    'true_severity': 'sev1',
                    'true_priority': 'p1',
                    'true_component': 'api-gateway',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': None,
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2002',
                    'true_severity': 'sev2',
                    'true_priority': 'p2',
                    'true_component': 'auth-service',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': None,
                    'needs_more_info': True},
                   {'ticket_id': 'BUG-2003',
                    'true_severity': 'sev2',
                    'true_priority': 'p2',
                    'true_component': 'user-service',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': None,
                    'needs_more_info': True},
                   {'ticket_id': 'BUG-2004',
                    'true_severity': 'sev2',
                    'true_priority': 'p2',
                    'true_component': 'payment-service',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': 'BUG-2002',
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2005',
                    'true_severity': 'sev1',
                    'true_priority': 'p1',
                    'true_component': 'web-app',
                    'true_assignee_team': 'frontend-web',
                    'duplicate_of': None,
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2006',
                    'true_severity': 'sev3',
                    'true_priority': 'p3',
                    'true_component': 'ios-app',
                    'true_assignee_team': 'mobile-ios',
                    'duplicate_of': None,
                    'needs_more_info': True},
                   {'ticket_id': 'BUG-2007',
                    'true_severity': 'sev1',
                    'true_priority': 'p1',
                    'true_component': 'android-app',
                    'true_assignee_team': 'mobile-android',
                    'duplicate_of': None,
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2008',
                    'true_severity': 'sev2',
                    'true_priority': 'p2',
                    'true_component': 'database',
                    'true_assignee_team': 'data-platform',
                    'duplicate_of': None,
                    'needs_more_info': True},
                   {'ticket_id': 'BUG-2009',
                    'true_severity': 'sev1',
                    'true_priority': 'p1',
                    'true_component': 'cache',
                    'true_assignee_team': 'infrastructure',
                    'duplicate_of': 'BUG-2005',
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2010',
                    'true_severity': 'sev2',
                    'true_priority': 'p2',
                    'true_component': 'cdn',
                    'true_assignee_team': 'infrastructure',
                    'duplicate_of': None,
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2011',
                    'true_severity': 'sev0',
                    'true_priority': 'p0',
                    'true_component': 'api-gateway',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': None,
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2012',
                    'true_severity': 'sev3',
                    'true_priority': 'p3',
                    'true_component': 'auth-service',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': None,
                    'needs_more_info': True},
                   {'ticket_id': 'BUG-2013',
                    'true_severity': 'sev2',
                    'true_priority': 'p2',
                    'true_component': 'user-service',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': None,
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2014',
                    'true_severity': 'sev1',
                    'true_priority': 'p1',
                    'true_component': 'payment-service',
                    'true_assignee_team': 'backend-api',
                    'duplicate_of': 'BUG-2001',
                    'needs_more_info': False},
                   {'ticket_id': 'BUG-2015',
                    'true_severity': 'sev3',
                    'true_priority': 'p3',
                    'true_component': 'web-app',
                    'true_assignee_team': 'frontend-web',
                    'duplicate_of': None,
                    'needs_more_info': False}]}
